// Core data types for Mealog

/**
 * Measurement units for ingredients
 */
export type MeasurementUnit =
  | "g" // grams
  | "kg" // kilograms
  | "ml" // milliliters
  | "l" // liters
  | "pcs" // pieces
  | "tbsp" // tablespoon
  | "tsp" // teaspoon
  | "cup"; // cup

/**
 * Ingredient with quantity and pricing
 */
export interface Ingredient {
  name: string;
  quantity: number;
  unit: MeasurementUnit;
  category?: IngredientCategory;
}

/**
 * Categories for grouping ingredients in shopping list
 */
export type IngredientCategory =
  | "dairy"
  | "produce"
  | "meat"
  | "grains"
  | "spices"
  | "other";

/**
 * Nutritional information for a meal
 */
export interface Nutrition {
  // Macronutrients (per serving)
  calories: number;
  protein: number; // grams
  carbs: number; // grams
  fat: number; // grams

  // Micronutrients (optional, as % of daily value)
  vitaminD?: number; // % daily value
  iron?: number; // % daily value
  calcium?: number; // % daily value
  vitaminC?: number; // % daily value
  fiber?: number; // grams
}

/**
 * Meal type labels
 */
export type MealType = "breakfast" | "lunch" | "dinner" | "snack";

/**
 * Additional meal labels/tags for filtering
 */
export type MealLabel =
  | "quick" // Quick to make (<30 min)
  | "delicates" // Delicate/special
  | "high-protein"
  | "low-carb"
  | "vegetarian"
  | "vegan"
  | "gluten-free"
  | "dairy-free";

/**
 * Recipe - can be URL or text instructions
 */
export interface Recipe {
  type: "url" | "text";
  content: string; // URL string or text instructions
}

/**
 * Complete meal/recipe data
 */
export interface Meal {
  id?: number; // Auto-generated by Dexie
  name: string;
  description: string;

  // Visual
  image: {
    type: "upload" | "url";
    content: string; // Base64 or URL
  };

  // Recipe instructions
  recipe: Recipe;

  // Ingredients list
  ingredients: Ingredient[];

  // Nutrition facts
  nutrition: Nutrition;

  // Meal classification
  mealType: MealType;
  labels: MealLabel[];

  // Serving info
  servings: number;

  // Sync Metadata
  householdId?: string; // Links to Firestore household
  lastUpdated?: number; // Timestamp for sync resolution
  dirty?: boolean; // True if needs syncing to Firestore
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Time of day for meal scheduling
 */
export interface MealTime {
  hour: number; // 0-23
  minute: number; // 0-59
  label?: string; // e.g., "8am", "12pm"
}

/**
 * Scheduled meal in a day
 */
export interface ScheduledMeal {
  mealId: number; // Reference to Meal.id
  time?: MealTime; // Optional scheduled time
  completed?: boolean; // For tracking if eaten
}

/**
 * Single day in weekly plan
 */
export interface DayPlan {
  date: Date;
  meals: ScheduledMeal[]; // Can have multiple meals/snacks
}

/**
 * Weekly meal plan
 */
export interface WeeklyPlan {
  id?: number; // Auto-generated by Dexie
  weekStart: number; // Monday timestamp (stored as number for IndexedDB queries)
  days: DayPlan[]; // 7 days

  // Sync Metadata
  householdId?: string; // Links to Firestore household
  lastUpdated?: number; // Timestamp for sync resolution
  dirty?: boolean; // True if needs syncing to Firestore
  createdAt: Date;
  updatedAt: Date;
}

/**
 * User Profile (Firestore representation)
 */
export interface UserProfile {
  uid: string;
  email: string | null;
  displayName: string | null;
  currentHouseholdId: string;
}

/**
 * Household (Firestore representation)
 */
export interface Household {
  id: string;
  name: string;
  members: string[]; // Array of uids
}

/**
 * Shopping list item (aggregated from weekly plan)
 */
export interface ShoppingListItem {
  id: string;
  ingredientName: string;
  totalQuantity: number;
  unit: MeasurementUnit;
  category: IngredientCategory;
  purchased?: boolean;
}

/**
 * Complete shopping list for a week
 */
export interface ShoppingList {
  id: number;
  weekStartDate: number; // Monday timestamp (matches WeeklyPlan.weekStart)
  items: ShoppingListItem[];
  createdAt: Date;
}

/**
 * Daily nutrition totals
 */
export interface DailyNutrition {
  date: Date;
  totalCalories: number;
  totalProtein: number;
  totalCarbs: number;
  totalFat: number;

  // Aggregated micronutrients
  vitaminD?: number;
  iron?: number;
  calcium?: number;

  // Deficiency flags
  deficiencies?: string[]; // e.g., ["Vitamin D", "Iron"]
}
